ALTER TABLE invoice  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE customer ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE product  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
