package com.MuhasebePlus.demo.report.entity;

public enum ReportType {
    PROFIT_LOSS, INCOME, EXPENSE, CASH_FLOW, AR_AGING, VAT_PREP, STOCK_STATUS, COLLECTION_PERFORMANCE, SLOW_INVENTORY,
    BUDGET_VARIANCE, BANK_RECONCILIATION, EXECUTIVE_SUMMARY,
    TRIAL_BALANCE, INCOME_STATEMENT, BALANCE_SHEET, JOURNAL_LISTING
}
