spring.application.name=MuhasebePlus

spring.datasource.url=jdbc:postgresql://localhost:5432/muhasebe_plus
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=RhSgrGCjvATFjaysOMn7MPix6AX6an73ZxucPisn91Q2
jwt.expiration=86400000
