// MuhasebePlus — route metadata (single source of truth)
export const ROUTE_META = {
  '/dashboard':   { crumbs: ['Dashboard'],                   icon: 'dashboard', label: 'Dashboard' },
  '/cari':        { crumbs: ['İşlemler', 'Cari Yönetimi'],   icon: 'users',     label: 'Cari (Müşteri)', shortcut: 'm' },
  '/fatura':      { crumbs: ['İşlemler', 'Fatura', 'Faturalar'], icon: 'invoice',   label: 'Faturalar',          shortcut: 'n' },
  '/fatura/odemeler': { crumbs: ['İşlemler', 'Fatura', 'Ödemeler'], icon: 'payment', label: 'Fatura Ödemeleri' },
  '/stok':        { crumbs: ['İşlemler', 'Stok Yönetimi'],   icon: 'box',       label: 'Stok',            shortcut: 's' },
  '/gelir-gider': { crumbs: ['İşlemler', 'Gelir / Gider'],   icon: 'swap',      label: 'Gelir / Gider',   shortcut: 'g' },
  '/banka':       { crumbs: ['İşlemler', 'Banka & Kasa'],    icon: 'bank',      label: 'Banka & Kasa',    shortcut: 'b' },
  '/sablon':      { crumbs: ['Otomasyon', 'Şablonlar'],      icon: 'template',  label: 'Şablonlar',       shortcut: 't' },
  '/rapor':       { crumbs: ['Otomasyon', 'Raporlar'],       icon: 'chart',     label: 'Raporlar',        shortcut: 'r' },
  '/butce':       { crumbs: ['Otomasyon', 'Bütçe'],         icon: 'flash',    label: 'Bütçe',           shortcut: 'u' },
  '/log':         { crumbs: ['Sistem', 'Loglar'],             icon: 'log',       label: 'Sistem Logları',  shortcut: 'l' },
  '/cek':         { crumbs: ['İşlemler', 'Çek / Senet'],     icon: 'cheque',    label: 'Çek / Senet',     shortcut: 'k' },
  '/hesap-plani': { crumbs: ['Muhasebe', 'Hesap Planı'],     icon: 'accounting',label: 'Hesap Planı' },
  '/yevmiye':     { crumbs: ['Muhasebe', 'Yevmiye Defteri'], icon: 'journal',   label: 'Yevmiye Defteri' },
  '/donem':       { crumbs: ['Muhasebe', 'Muhasebe Dönemi'], icon: 'calendar',  label: 'Muhasebe Dönemi' },
  '/beyanname':   { crumbs: ['Muhasebe', 'Beyannameler'],    icon: 'document',  label: 'Beyannameler' },
  '/edefter':     { crumbs: ['Muhasebe', 'e-Defter'],        icon: 'archive',   label: 'e-Defter' },
  '/sabit-kiymet':     { crumbs: ['Muhasebe', 'Sabit Kıymetler'], icon: 'building', label: 'Sabit Kıymetler' },
  '/admin':              { crumbs: ['Yönetim', 'Genel Bakış'],     icon: 'shield',   label: 'Yönetim Paneli',     adminOnly: true },
  '/admin/kullanicilar': { crumbs: ['Yönetim', 'Kullanıcılar'],    icon: 'users',    label: 'Kullanıcı Yönetimi', adminOnly: true },
  '/admin/sirketler':    { crumbs: ['Yönetim', 'Şirketler'],       icon: 'building', label: 'Şirket Yönetimi',    adminOnly: true },
  '/admin/ayarlar':      { crumbs: ['Yönetim', 'Sistem Ayarları'], icon: 'settings', label: 'Sistem Ayarları',    adminOnly: true },
  '/admin/loglar':       { crumbs: ['Yönetim', 'Loglar & Denetim'],icon: 'log',      label: 'Loglar & Denetim',   adminOnly: true },
};

export const NAV = [
  { section: 'GENEL' },
  { to: '/dashboard', label: 'Dashboard', icon: 'dashboard' },
  { section: 'İŞLEMLER' },
  { to: '/cari',        label: 'Cari (Müşteri)', icon: 'users' },
  { to: '/fatura', label: 'Fatura', icon: 'invoice', children: [
    { to: '/fatura', label: 'Faturalar' },
    { to: '/fatura/odemeler', label: 'Fatura Ödemeleri' },
  ]},
  { to: '/stok',        label: 'Stok',            icon: 'box' },
  { to: '/gelir-gider', label: 'Gelir / Gider',   icon: 'swap' },
  { to: '/banka',       label: 'Banka & Kasa',    icon: 'bank' },
  { to: '/cek',         label: 'Çek / Senet',     icon: 'cheque' },
  { section: 'MUHASEBE' },
  { to: '/hesap-plani', label: 'Hesap Planı',      icon: 'accounting' },
  { to: '/yevmiye',     label: 'Yevmiye Defteri',  icon: 'journal' },
  { to: '/donem',       label: 'Muhasebe Dönemi',  icon: 'calendar' },
  { to: '/beyanname',   label: 'Beyannameler',      icon: 'document' },
  { to: '/edefter',     label: 'e-Defter',          icon: 'archive' },
  { to: '/sabit-kiymet',     label: 'Sabit Kıymetler',  icon: 'building' },
  { section: 'OTOMASYON' },
  { to: '/sablon', label: 'Şablonlar', icon: 'template' },
  { to: '/rapor',  label: 'Raporlar',  icon: 'chart' },
  { to: '/butce',  label: 'Bütçe',     icon: 'flash' },
  { section: 'SİSTEM' },
  { to: '/log', label: 'Sistem Logları', icon: 'log' },
  { section: 'YÖNETİM', adminOnly: true },
  { to: '/admin',              label: 'Genel Bakış',      icon: 'shield',   adminOnly: true },
  { to: '/admin/kullanicilar', label: 'Kullanıcılar',     icon: 'users',    adminOnly: true },
  { to: '/admin/sirketler',    label: 'Şirketler',        icon: 'building', adminOnly: true },
  { to: '/admin/ayarlar',      label: 'Sistem Ayarları',  icon: 'settings', adminOnly: true },
  { to: '/admin/loglar',       label: 'Loglar & Denetim', icon: 'log',      adminOnly: true },
];
